### ISSUE TITLE
从相册选择，无法选择本地图片

### ISSUE THREAD

**Issue by bewuluck0912** [richardchien/jigsaw-android#2]
从相册选择，可以进入本地查看文件，但选择图片，没有反应。

**Comment by stdrc** [comment]
这个太久之前的项目啦，已经不维护了，可能已经存在接口不兼容的问题

henter0827 <notifications@github.com>于2019年5月21日 周二19:28写道：

**Comment by henter0827** [comment]
看了下代码，好像是权限问题
